remote_theme: "mmistakes/jekyll-theme-basically-basic"

# Site Settings
lang: en-GB
title: DigiBP - Digitalisation of Business Processes
email: andreas.martin@fhnw.ch
description: "This is the portal for the Digitalisation of Business Processes module."
url: "https://digibp.github.io"
repository: "DigiBP/digibp.github.io"
author:
  name: Andreas Martin
github_username: DigiBP
logo: https://avatars3.githubusercontent.com/u/25099178
search: true
search_full_content: true
search_provider: lunr

# Front Matter Defaults
defaults:
    values:
      layout: home
read_time: true
